apiVersion: apps/v1
kind: Deployment
metadata:
  name: victim
  labels:
    app: victim
spec:
  replicas: 1
  selector:
    matchLabels:
      app: victim
  template:
    metadata:
      labels:
        app: victim
    spec:
      containers:
      - name: victim-container
        image: nichtsfrei/victim:latest
        imagePullPolicy: Always
