name: publish

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: docker/setup-buildx-action@v1
      - uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - run: cd lwe && DOCKER_BUILDKIT=1 docker build -t ${{ github.repository }}-simulate-website .
      - run: docker push ${{ github.repository }}-simulate-website
