name: publish

on:
  push:
    branches: [ main ]

jobs:
  build:
    permissions:
      contents: read
      packages: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v2
      - uses: docker/login-action@v3
        with:
          registry: ${{ vars.IMAGE_REGISTRY }}
          username: ${{ secrets.GREENBONE_BOT }}
          password: ${{ secrets.GREENBONE_BOT_PACKAGES_WRITE_TOKEN }}
      - run: make push
